#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFStokTakip.Fonksiyonlar
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GFOtomasyon")]
	public partial class DataBaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_UrunTuru(TBL_UrunTuru instance);
    partial void UpdateTBL_UrunTuru(TBL_UrunTuru instance);
    partial void DeleteTBL_UrunTuru(TBL_UrunTuru instance);
    partial void InsertTBL_Temin(TBL_Temin instance);
    partial void UpdateTBL_Temin(TBL_Temin instance);
    partial void DeleteTBL_Temin(TBL_Temin instance);
    partial void InsertTBL_UrunMarka(TBL_UrunMarka instance);
    partial void UpdateTBL_UrunMarka(TBL_UrunMarka instance);
    partial void DeleteTBL_UrunMarka(TBL_UrunMarka instance);
    partial void InsertTBL_Urunler(TBL_Urunler instance);
    partial void UpdateTBL_Urunler(TBL_Urunler instance);
    partial void DeleteTBL_Urunler(TBL_Urunler instance);
    partial void InsertTBL_Departmanlar(TBL_Departmanlar instance);
    partial void UpdateTBL_Departmanlar(TBL_Departmanlar instance);
    partial void DeleteTBL_Departmanlar(TBL_Departmanlar instance);
    partial void InsertTBL_Zimmetler(TBL_Zimmetler instance);
    partial void UpdateTBL_Zimmetler(TBL_Zimmetler instance);
    partial void DeleteTBL_Zimmetler(TBL_Zimmetler instance);
    partial void InsertTBL_Personeller(TBL_Personeller instance);
    partial void UpdateTBL_Personeller(TBL_Personeller instance);
    partial void DeleteTBL_Personeller(TBL_Personeller instance);
    partial void InsertTBL_ZimmetHata(TBL_ZimmetHata instance);
    partial void UpdateTBL_ZimmetHata(TBL_ZimmetHata instance);
    partial void DeleteTBL_ZimmetHata(TBL_ZimmetHata instance);
    #endregion
		
		public DataBaseDataContext() : 
				base(global::GFStokTakip.Properties.Settings.Default.GFOtomasyonConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_UrunTuru> TBL_UrunTurus
		{
			get
			{
				return this.GetTable<TBL_UrunTuru>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Temin> TBL_Temins
		{
			get
			{
				return this.GetTable<TBL_Temin>();
			}
		}
		
		public System.Data.Linq.Table<TBL_UrunMarka> TBL_UrunMarkas
		{
			get
			{
				return this.GetTable<TBL_UrunMarka>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Urunler> TBL_Urunlers
		{
			get
			{
				return this.GetTable<TBL_Urunler>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Departmanlar> TBL_Departmanlars
		{
			get
			{
				return this.GetTable<TBL_Departmanlar>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Zimmetler> TBL_Zimmetlers
		{
			get
			{
				return this.GetTable<TBL_Zimmetler>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Personeller> TBL_Personellers
		{
			get
			{
				return this.GetTable<TBL_Personeller>();
			}
		}
		
		public System.Data.Linq.Table<TBL_ZimmetIadeNeden> TBL_ZimmetIadeNedens
		{
			get
			{
				return this.GetTable<TBL_ZimmetIadeNeden>();
			}
		}
		
		public System.Data.Linq.Table<VW_Urunler> VW_Urunlers
		{
			get
			{
				return this.GetTable<VW_Urunler>();
			}
		}
		
		public System.Data.Linq.Table<VW_ZimmetListesi> VW_ZimmetListesis
		{
			get
			{
				return this.GetTable<VW_ZimmetListesi>();
			}
		}
		
		public System.Data.Linq.Table<TBL_ZimmetHata> TBL_ZimmetHatas
		{
			get
			{
				return this.GetTable<TBL_ZimmetHata>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_UrunTuru")]
	public partial class TBL_UrunTuru : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _UrunTuruKodu;
		
		private string _UrunTuruAdi;
		
		private System.Nullable<System.DateTime> _UrunTuruSaveDate;
		
		private System.Nullable<int> _UrunTuruSaveUser;
		
		private System.Nullable<System.DateTime> _UrunTuruEditDate;
		
		private System.Nullable<int> _UrunTuruEditUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUrunTuruKoduChanging(string value);
    partial void OnUrunTuruKoduChanged();
    partial void OnUrunTuruAdiChanging(string value);
    partial void OnUrunTuruAdiChanged();
    partial void OnUrunTuruSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUrunTuruSaveDateChanged();
    partial void OnUrunTuruSaveUserChanging(System.Nullable<int> value);
    partial void OnUrunTuruSaveUserChanged();
    partial void OnUrunTuruEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUrunTuruEditDateChanged();
    partial void OnUrunTuruEditUserChanging(System.Nullable<int> value);
    partial void OnUrunTuruEditUserChanged();
    #endregion
		
		public TBL_UrunTuru()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunTuruKodu", DbType="NVarChar(30)")]
		public string UrunTuruKodu
		{
			get
			{
				return this._UrunTuruKodu;
			}
			set
			{
				if ((this._UrunTuruKodu != value))
				{
					this.OnUrunTuruKoduChanging(value);
					this.SendPropertyChanging();
					this._UrunTuruKodu = value;
					this.SendPropertyChanged("UrunTuruKodu");
					this.OnUrunTuruKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunTuruAdi", DbType="NVarChar(50)")]
		public string UrunTuruAdi
		{
			get
			{
				return this._UrunTuruAdi;
			}
			set
			{
				if ((this._UrunTuruAdi != value))
				{
					this.OnUrunTuruAdiChanging(value);
					this.SendPropertyChanging();
					this._UrunTuruAdi = value;
					this.SendPropertyChanged("UrunTuruAdi");
					this.OnUrunTuruAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunTuruSaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UrunTuruSaveDate
		{
			get
			{
				return this._UrunTuruSaveDate;
			}
			set
			{
				if ((this._UrunTuruSaveDate != value))
				{
					this.OnUrunTuruSaveDateChanging(value);
					this.SendPropertyChanging();
					this._UrunTuruSaveDate = value;
					this.SendPropertyChanged("UrunTuruSaveDate");
					this.OnUrunTuruSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunTuruSaveUser", DbType="Int")]
		public System.Nullable<int> UrunTuruSaveUser
		{
			get
			{
				return this._UrunTuruSaveUser;
			}
			set
			{
				if ((this._UrunTuruSaveUser != value))
				{
					this.OnUrunTuruSaveUserChanging(value);
					this.SendPropertyChanging();
					this._UrunTuruSaveUser = value;
					this.SendPropertyChanged("UrunTuruSaveUser");
					this.OnUrunTuruSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunTuruEditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UrunTuruEditDate
		{
			get
			{
				return this._UrunTuruEditDate;
			}
			set
			{
				if ((this._UrunTuruEditDate != value))
				{
					this.OnUrunTuruEditDateChanging(value);
					this.SendPropertyChanging();
					this._UrunTuruEditDate = value;
					this.SendPropertyChanged("UrunTuruEditDate");
					this.OnUrunTuruEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunTuruEditUser", DbType="Int")]
		public System.Nullable<int> UrunTuruEditUser
		{
			get
			{
				return this._UrunTuruEditUser;
			}
			set
			{
				if ((this._UrunTuruEditUser != value))
				{
					this.OnUrunTuruEditUserChanging(value);
					this.SendPropertyChanging();
					this._UrunTuruEditUser = value;
					this.SendPropertyChanged("UrunTuruEditUser");
					this.OnUrunTuruEditUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Temin")]
	public partial class TBL_Temin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TeminKodu;
		
		private string _TeminAdi;
		
		private System.Nullable<System.DateTime> _TeminSaveDate;
		
		private System.Nullable<int> _TeminSaveUser;
		
		private System.Nullable<System.DateTime> _TeminEditDate;
		
		private System.Nullable<int> _TeminEditUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTeminKoduChanging(string value);
    partial void OnTeminKoduChanged();
    partial void OnTeminAdiChanging(string value);
    partial void OnTeminAdiChanged();
    partial void OnTeminSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnTeminSaveDateChanged();
    partial void OnTeminSaveUserChanging(System.Nullable<int> value);
    partial void OnTeminSaveUserChanged();
    partial void OnTeminEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnTeminEditDateChanged();
    partial void OnTeminEditUserChanging(System.Nullable<int> value);
    partial void OnTeminEditUserChanged();
    #endregion
		
		public TBL_Temin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeminKodu", DbType="NVarChar(30)")]
		public string TeminKodu
		{
			get
			{
				return this._TeminKodu;
			}
			set
			{
				if ((this._TeminKodu != value))
				{
					this.OnTeminKoduChanging(value);
					this.SendPropertyChanging();
					this._TeminKodu = value;
					this.SendPropertyChanged("TeminKodu");
					this.OnTeminKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeminAdi", DbType="NVarChar(50)")]
		public string TeminAdi
		{
			get
			{
				return this._TeminAdi;
			}
			set
			{
				if ((this._TeminAdi != value))
				{
					this.OnTeminAdiChanging(value);
					this.SendPropertyChanging();
					this._TeminAdi = value;
					this.SendPropertyChanged("TeminAdi");
					this.OnTeminAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeminSaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> TeminSaveDate
		{
			get
			{
				return this._TeminSaveDate;
			}
			set
			{
				if ((this._TeminSaveDate != value))
				{
					this.OnTeminSaveDateChanging(value);
					this.SendPropertyChanging();
					this._TeminSaveDate = value;
					this.SendPropertyChanged("TeminSaveDate");
					this.OnTeminSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeminSaveUser", DbType="Int")]
		public System.Nullable<int> TeminSaveUser
		{
			get
			{
				return this._TeminSaveUser;
			}
			set
			{
				if ((this._TeminSaveUser != value))
				{
					this.OnTeminSaveUserChanging(value);
					this.SendPropertyChanging();
					this._TeminSaveUser = value;
					this.SendPropertyChanged("TeminSaveUser");
					this.OnTeminSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeminEditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> TeminEditDate
		{
			get
			{
				return this._TeminEditDate;
			}
			set
			{
				if ((this._TeminEditDate != value))
				{
					this.OnTeminEditDateChanging(value);
					this.SendPropertyChanging();
					this._TeminEditDate = value;
					this.SendPropertyChanged("TeminEditDate");
					this.OnTeminEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeminEditUser", DbType="Int")]
		public System.Nullable<int> TeminEditUser
		{
			get
			{
				return this._TeminEditUser;
			}
			set
			{
				if ((this._TeminEditUser != value))
				{
					this.OnTeminEditUserChanging(value);
					this.SendPropertyChanging();
					this._TeminEditUser = value;
					this.SendPropertyChanged("TeminEditUser");
					this.OnTeminEditUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_UrunMarka")]
	public partial class TBL_UrunMarka : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _MarkaAdi;
		
		private string _MarkaKodu;
		
		private System.Nullable<System.DateTime> _MarkaSaveDate;
		
		private System.Nullable<int> _MarkaSaveUser;
		
		private System.Nullable<int> _MarkaEditUser;
		
		private System.Nullable<System.DateTime> _MarkaEditDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMarkaAdiChanging(string value);
    partial void OnMarkaAdiChanged();
    partial void OnMarkaKoduChanging(string value);
    partial void OnMarkaKoduChanged();
    partial void OnMarkaSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnMarkaSaveDateChanged();
    partial void OnMarkaSaveUserChanging(System.Nullable<int> value);
    partial void OnMarkaSaveUserChanged();
    partial void OnMarkaEditUserChanging(System.Nullable<int> value);
    partial void OnMarkaEditUserChanged();
    partial void OnMarkaEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnMarkaEditDateChanged();
    #endregion
		
		public TBL_UrunMarka()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkaAdi", DbType="NVarChar(30)")]
		public string MarkaAdi
		{
			get
			{
				return this._MarkaAdi;
			}
			set
			{
				if ((this._MarkaAdi != value))
				{
					this.OnMarkaAdiChanging(value);
					this.SendPropertyChanging();
					this._MarkaAdi = value;
					this.SendPropertyChanged("MarkaAdi");
					this.OnMarkaAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkaKodu", DbType="NVarChar(30)")]
		public string MarkaKodu
		{
			get
			{
				return this._MarkaKodu;
			}
			set
			{
				if ((this._MarkaKodu != value))
				{
					this.OnMarkaKoduChanging(value);
					this.SendPropertyChanging();
					this._MarkaKodu = value;
					this.SendPropertyChanged("MarkaKodu");
					this.OnMarkaKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkaSaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> MarkaSaveDate
		{
			get
			{
				return this._MarkaSaveDate;
			}
			set
			{
				if ((this._MarkaSaveDate != value))
				{
					this.OnMarkaSaveDateChanging(value);
					this.SendPropertyChanging();
					this._MarkaSaveDate = value;
					this.SendPropertyChanged("MarkaSaveDate");
					this.OnMarkaSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkaSaveUser", DbType="Int")]
		public System.Nullable<int> MarkaSaveUser
		{
			get
			{
				return this._MarkaSaveUser;
			}
			set
			{
				if ((this._MarkaSaveUser != value))
				{
					this.OnMarkaSaveUserChanging(value);
					this.SendPropertyChanging();
					this._MarkaSaveUser = value;
					this.SendPropertyChanged("MarkaSaveUser");
					this.OnMarkaSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkaEditUser", DbType="Int")]
		public System.Nullable<int> MarkaEditUser
		{
			get
			{
				return this._MarkaEditUser;
			}
			set
			{
				if ((this._MarkaEditUser != value))
				{
					this.OnMarkaEditUserChanging(value);
					this.SendPropertyChanging();
					this._MarkaEditUser = value;
					this.SendPropertyChanged("MarkaEditUser");
					this.OnMarkaEditUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkaEditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> MarkaEditDate
		{
			get
			{
				return this._MarkaEditDate;
			}
			set
			{
				if ((this._MarkaEditDate != value))
				{
					this.OnMarkaEditDateChanging(value);
					this.SendPropertyChanging();
					this._MarkaEditDate = value;
					this.SendPropertyChanged("MarkaEditDate");
					this.OnMarkaEditDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Urunler")]
	public partial class TBL_Urunler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _UrunBarkod;
		
		private string _UrunKodu;
		
		private string _UrunAdi;
		
		private System.Nullable<decimal> _UrunAlisFiyat;
		
		private System.Nullable<int> _UrunMarkaID;
		
		private System.Nullable<int> _UrunTuruID;
		
		private System.Nullable<int> _UrunTeminID;
		
		private string _UrunTuruAciklama;
		
		private System.Nullable<int> _UrunStokMiktari;
		
		private System.Nullable<System.DateTime> _UrunAlisTarihi;
		
		private string _UrunTeminSubeAdi;
		
		private System.Nullable<int> _UrunSaveUser;
		
		private System.Nullable<System.DateTime> _UrunSaveDate;
		
		private System.Nullable<int> _UrunEditUser;
		
		private System.Nullable<System.DateTime> _UrunEditDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUrunBarkodChanging(string value);
    partial void OnUrunBarkodChanged();
    partial void OnUrunKoduChanging(string value);
    partial void OnUrunKoduChanged();
    partial void OnUrunAdiChanging(string value);
    partial void OnUrunAdiChanged();
    partial void OnUrunAlisFiyatChanging(System.Nullable<decimal> value);
    partial void OnUrunAlisFiyatChanged();
    partial void OnUrunMarkaIDChanging(System.Nullable<int> value);
    partial void OnUrunMarkaIDChanged();
    partial void OnUrunTuruIDChanging(System.Nullable<int> value);
    partial void OnUrunTuruIDChanged();
    partial void OnUrunTeminIDChanging(System.Nullable<int> value);
    partial void OnUrunTeminIDChanged();
    partial void OnUrunTuruAciklamaChanging(string value);
    partial void OnUrunTuruAciklamaChanged();
    partial void OnUrunStokMiktariChanging(System.Nullable<int> value);
    partial void OnUrunStokMiktariChanged();
    partial void OnUrunAlisTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnUrunAlisTarihiChanged();
    partial void OnUrunTeminSubeAdiChanging(string value);
    partial void OnUrunTeminSubeAdiChanged();
    partial void OnUrunSaveUserChanging(System.Nullable<int> value);
    partial void OnUrunSaveUserChanged();
    partial void OnUrunSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUrunSaveDateChanged();
    partial void OnUrunEditUserChanging(System.Nullable<int> value);
    partial void OnUrunEditUserChanged();
    partial void OnUrunEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUrunEditDateChanged();
    #endregion
		
		public TBL_Urunler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunBarkod", DbType="NVarChar(30)")]
		public string UrunBarkod
		{
			get
			{
				return this._UrunBarkod;
			}
			set
			{
				if ((this._UrunBarkod != value))
				{
					this.OnUrunBarkodChanging(value);
					this.SendPropertyChanging();
					this._UrunBarkod = value;
					this.SendPropertyChanged("UrunBarkod");
					this.OnUrunBarkodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunKodu", DbType="NVarChar(20)")]
		public string UrunKodu
		{
			get
			{
				return this._UrunKodu;
			}
			set
			{
				if ((this._UrunKodu != value))
				{
					this.OnUrunKoduChanging(value);
					this.SendPropertyChanging();
					this._UrunKodu = value;
					this.SendPropertyChanged("UrunKodu");
					this.OnUrunKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunAdi", DbType="NVarChar(50)")]
		public string UrunAdi
		{
			get
			{
				return this._UrunAdi;
			}
			set
			{
				if ((this._UrunAdi != value))
				{
					this.OnUrunAdiChanging(value);
					this.SendPropertyChanging();
					this._UrunAdi = value;
					this.SendPropertyChanged("UrunAdi");
					this.OnUrunAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunAlisFiyat", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> UrunAlisFiyat
		{
			get
			{
				return this._UrunAlisFiyat;
			}
			set
			{
				if ((this._UrunAlisFiyat != value))
				{
					this.OnUrunAlisFiyatChanging(value);
					this.SendPropertyChanging();
					this._UrunAlisFiyat = value;
					this.SendPropertyChanged("UrunAlisFiyat");
					this.OnUrunAlisFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunMarkaID", DbType="Int")]
		public System.Nullable<int> UrunMarkaID
		{
			get
			{
				return this._UrunMarkaID;
			}
			set
			{
				if ((this._UrunMarkaID != value))
				{
					this.OnUrunMarkaIDChanging(value);
					this.SendPropertyChanging();
					this._UrunMarkaID = value;
					this.SendPropertyChanged("UrunMarkaID");
					this.OnUrunMarkaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunTuruID", DbType="Int")]
		public System.Nullable<int> UrunTuruID
		{
			get
			{
				return this._UrunTuruID;
			}
			set
			{
				if ((this._UrunTuruID != value))
				{
					this.OnUrunTuruIDChanging(value);
					this.SendPropertyChanging();
					this._UrunTuruID = value;
					this.SendPropertyChanged("UrunTuruID");
					this.OnUrunTuruIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunTeminID", DbType="Int")]
		public System.Nullable<int> UrunTeminID
		{
			get
			{
				return this._UrunTeminID;
			}
			set
			{
				if ((this._UrunTeminID != value))
				{
					this.OnUrunTeminIDChanging(value);
					this.SendPropertyChanging();
					this._UrunTeminID = value;
					this.SendPropertyChanged("UrunTeminID");
					this.OnUrunTeminIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunTuruAciklama", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string UrunTuruAciklama
		{
			get
			{
				return this._UrunTuruAciklama;
			}
			set
			{
				if ((this._UrunTuruAciklama != value))
				{
					this.OnUrunTuruAciklamaChanging(value);
					this.SendPropertyChanging();
					this._UrunTuruAciklama = value;
					this.SendPropertyChanged("UrunTuruAciklama");
					this.OnUrunTuruAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunStokMiktari", DbType="Int")]
		public System.Nullable<int> UrunStokMiktari
		{
			get
			{
				return this._UrunStokMiktari;
			}
			set
			{
				if ((this._UrunStokMiktari != value))
				{
					this.OnUrunStokMiktariChanging(value);
					this.SendPropertyChanging();
					this._UrunStokMiktari = value;
					this.SendPropertyChanged("UrunStokMiktari");
					this.OnUrunStokMiktariChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunAlisTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> UrunAlisTarihi
		{
			get
			{
				return this._UrunAlisTarihi;
			}
			set
			{
				if ((this._UrunAlisTarihi != value))
				{
					this.OnUrunAlisTarihiChanging(value);
					this.SendPropertyChanging();
					this._UrunAlisTarihi = value;
					this.SendPropertyChanged("UrunAlisTarihi");
					this.OnUrunAlisTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunTeminSubeAdi", DbType="NVarChar(50)")]
		public string UrunTeminSubeAdi
		{
			get
			{
				return this._UrunTeminSubeAdi;
			}
			set
			{
				if ((this._UrunTeminSubeAdi != value))
				{
					this.OnUrunTeminSubeAdiChanging(value);
					this.SendPropertyChanging();
					this._UrunTeminSubeAdi = value;
					this.SendPropertyChanged("UrunTeminSubeAdi");
					this.OnUrunTeminSubeAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunSaveUser", DbType="Int")]
		public System.Nullable<int> UrunSaveUser
		{
			get
			{
				return this._UrunSaveUser;
			}
			set
			{
				if ((this._UrunSaveUser != value))
				{
					this.OnUrunSaveUserChanging(value);
					this.SendPropertyChanging();
					this._UrunSaveUser = value;
					this.SendPropertyChanged("UrunSaveUser");
					this.OnUrunSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunSaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UrunSaveDate
		{
			get
			{
				return this._UrunSaveDate;
			}
			set
			{
				if ((this._UrunSaveDate != value))
				{
					this.OnUrunSaveDateChanging(value);
					this.SendPropertyChanging();
					this._UrunSaveDate = value;
					this.SendPropertyChanged("UrunSaveDate");
					this.OnUrunSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunEditUser", DbType="Int")]
		public System.Nullable<int> UrunEditUser
		{
			get
			{
				return this._UrunEditUser;
			}
			set
			{
				if ((this._UrunEditUser != value))
				{
					this.OnUrunEditUserChanging(value);
					this.SendPropertyChanging();
					this._UrunEditUser = value;
					this.SendPropertyChanged("UrunEditUser");
					this.OnUrunEditUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunEditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UrunEditDate
		{
			get
			{
				return this._UrunEditDate;
			}
			set
			{
				if ((this._UrunEditDate != value))
				{
					this.OnUrunEditDateChanging(value);
					this.SendPropertyChanging();
					this._UrunEditDate = value;
					this.SendPropertyChanged("UrunEditDate");
					this.OnUrunEditDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Departmanlar")]
	public partial class TBL_Departmanlar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _DepartmanAdi;
		
		private string _DepartmanKodu;
		
		private System.Nullable<System.DateTime> _SaveDate;
		
		private System.Nullable<int> _SaveUser;
		
		private System.Nullable<System.DateTime> _EditDate;
		
		private System.Nullable<int> _EditUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDepartmanAdiChanging(string value);
    partial void OnDepartmanAdiChanged();
    partial void OnDepartmanKoduChanging(string value);
    partial void OnDepartmanKoduChanged();
    partial void OnSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSaveDateChanged();
    partial void OnSaveUserChanging(System.Nullable<int> value);
    partial void OnSaveUserChanged();
    partial void OnEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEditDateChanged();
    partial void OnEditUserChanging(System.Nullable<int> value);
    partial void OnEditUserChanged();
    #endregion
		
		public TBL_Departmanlar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmanAdi", DbType="NVarChar(30)")]
		public string DepartmanAdi
		{
			get
			{
				return this._DepartmanAdi;
			}
			set
			{
				if ((this._DepartmanAdi != value))
				{
					this.OnDepartmanAdiChanging(value);
					this.SendPropertyChanging();
					this._DepartmanAdi = value;
					this.SendPropertyChanged("DepartmanAdi");
					this.OnDepartmanAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmanKodu", DbType="NVarChar(30)")]
		public string DepartmanKodu
		{
			get
			{
				return this._DepartmanKodu;
			}
			set
			{
				if ((this._DepartmanKodu != value))
				{
					this.OnDepartmanKoduChanging(value);
					this.SendPropertyChanging();
					this._DepartmanKodu = value;
					this.SendPropertyChanged("DepartmanKodu");
					this.OnDepartmanKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SaveDate
		{
			get
			{
				return this._SaveDate;
			}
			set
			{
				if ((this._SaveDate != value))
				{
					this.OnSaveDateChanging(value);
					this.SendPropertyChanging();
					this._SaveDate = value;
					this.SendPropertyChanged("SaveDate");
					this.OnSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveUser", DbType="Int")]
		public System.Nullable<int> SaveUser
		{
			get
			{
				return this._SaveUser;
			}
			set
			{
				if ((this._SaveUser != value))
				{
					this.OnSaveUserChanging(value);
					this.SendPropertyChanging();
					this._SaveUser = value;
					this.SendPropertyChanged("SaveUser");
					this.OnSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this.OnEditDateChanging(value);
					this.SendPropertyChanging();
					this._EditDate = value;
					this.SendPropertyChanged("EditDate");
					this.OnEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditUser", DbType="Int")]
		public System.Nullable<int> EditUser
		{
			get
			{
				return this._EditUser;
			}
			set
			{
				if ((this._EditUser != value))
				{
					this.OnEditUserChanging(value);
					this.SendPropertyChanging();
					this._EditUser = value;
					this.SendPropertyChanged("EditUser");
					this.OnEditUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Zimmetler")]
	public partial class TBL_Zimmetler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _ZimmetKodu;
		
		private System.Nullable<int> _PersonelID;
		
		private System.Nullable<int> _UrunID;
		
		private System.Nullable<int> _DepartmanID;
		
		private System.Nullable<System.DateTime> _TeslimTarihi;
		
		private System.Nullable<int> _SaveUser;
		
		private System.Nullable<System.DateTime> _SaveDate;
		
		private System.Nullable<int> _EditUser;
		
		private System.Nullable<System.DateTime> _EditDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnZimmetKoduChanging(string value);
    partial void OnZimmetKoduChanged();
    partial void OnPersonelIDChanging(System.Nullable<int> value);
    partial void OnPersonelIDChanged();
    partial void OnUrunIDChanging(System.Nullable<int> value);
    partial void OnUrunIDChanged();
    partial void OnDepartmanIDChanging(System.Nullable<int> value);
    partial void OnDepartmanIDChanged();
    partial void OnTeslimTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnTeslimTarihiChanged();
    partial void OnSaveUserChanging(System.Nullable<int> value);
    partial void OnSaveUserChanged();
    partial void OnSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSaveDateChanged();
    partial void OnEditUserChanging(System.Nullable<int> value);
    partial void OnEditUserChanged();
    partial void OnEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEditDateChanged();
    #endregion
		
		public TBL_Zimmetler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZimmetKodu", DbType="NVarChar(50)")]
		public string ZimmetKodu
		{
			get
			{
				return this._ZimmetKodu;
			}
			set
			{
				if ((this._ZimmetKodu != value))
				{
					this.OnZimmetKoduChanging(value);
					this.SendPropertyChanging();
					this._ZimmetKodu = value;
					this.SendPropertyChanged("ZimmetKodu");
					this.OnZimmetKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelID", DbType="Int")]
		public System.Nullable<int> PersonelID
		{
			get
			{
				return this._PersonelID;
			}
			set
			{
				if ((this._PersonelID != value))
				{
					this.OnPersonelIDChanging(value);
					this.SendPropertyChanging();
					this._PersonelID = value;
					this.SendPropertyChanged("PersonelID");
					this.OnPersonelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunID", DbType="Int")]
		public System.Nullable<int> UrunID
		{
			get
			{
				return this._UrunID;
			}
			set
			{
				if ((this._UrunID != value))
				{
					this.OnUrunIDChanging(value);
					this.SendPropertyChanging();
					this._UrunID = value;
					this.SendPropertyChanged("UrunID");
					this.OnUrunIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmanID", DbType="Int")]
		public System.Nullable<int> DepartmanID
		{
			get
			{
				return this._DepartmanID;
			}
			set
			{
				if ((this._DepartmanID != value))
				{
					this.OnDepartmanIDChanging(value);
					this.SendPropertyChanging();
					this._DepartmanID = value;
					this.SendPropertyChanged("DepartmanID");
					this.OnDepartmanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeslimTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> TeslimTarihi
		{
			get
			{
				return this._TeslimTarihi;
			}
			set
			{
				if ((this._TeslimTarihi != value))
				{
					this.OnTeslimTarihiChanging(value);
					this.SendPropertyChanging();
					this._TeslimTarihi = value;
					this.SendPropertyChanged("TeslimTarihi");
					this.OnTeslimTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveUser", DbType="Int")]
		public System.Nullable<int> SaveUser
		{
			get
			{
				return this._SaveUser;
			}
			set
			{
				if ((this._SaveUser != value))
				{
					this.OnSaveUserChanging(value);
					this.SendPropertyChanging();
					this._SaveUser = value;
					this.SendPropertyChanged("SaveUser");
					this.OnSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SaveDate
		{
			get
			{
				return this._SaveDate;
			}
			set
			{
				if ((this._SaveDate != value))
				{
					this.OnSaveDateChanging(value);
					this.SendPropertyChanging();
					this._SaveDate = value;
					this.SendPropertyChanged("SaveDate");
					this.OnSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditUser", DbType="Int")]
		public System.Nullable<int> EditUser
		{
			get
			{
				return this._EditUser;
			}
			set
			{
				if ((this._EditUser != value))
				{
					this.OnEditUserChanging(value);
					this.SendPropertyChanging();
					this._EditUser = value;
					this.SendPropertyChanged("EditUser");
					this.OnEditUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this.OnEditDateChanging(value);
					this.SendPropertyChanging();
					this._EditDate = value;
					this.SendPropertyChanged("EditDate");
					this.OnEditDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Personeller")]
	public partial class TBL_Personeller : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _PersonelKodu;
		
		private string _PersonelAdiSoyadi;
		
		private string _PersonelKullaniciAdi;
		
		private string _PersonelSifre;
		
		private string _PersonelRutbe;
		
		private System.Nullable<bool> _PersonelAktif;
		
		private string _SorumluOldDepartman;
		
		private System.Nullable<int> _DepartmanID;
		
		private System.Nullable<System.DateTime> _IseBaslangicTarihi;
		
		private System.Nullable<System.DateTime> _AyrilmaTarihi;
		
		private string _Sehir;
		
		private string _Ilce;
		
		private string _Adres;
		
		private string _Telefon1;
		
		private string _Telefon2;
		
		private string _WebAdres;
		
		private string _Mail;
		
		private System.Nullable<System.DateTime> _SaveDate;
		
		private System.Nullable<int> _SaveUser;
		
		private System.Nullable<System.DateTime> _EditDate;
		
		private System.Nullable<int> _EditUser;
		
		private System.Nullable<System.DateTime> _LastLogin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPersonelKoduChanging(string value);
    partial void OnPersonelKoduChanged();
    partial void OnPersonelAdiSoyadiChanging(string value);
    partial void OnPersonelAdiSoyadiChanged();
    partial void OnPersonelKullaniciAdiChanging(string value);
    partial void OnPersonelKullaniciAdiChanged();
    partial void OnPersonelSifreChanging(string value);
    partial void OnPersonelSifreChanged();
    partial void OnPersonelRutbeChanging(string value);
    partial void OnPersonelRutbeChanged();
    partial void OnPersonelAktifChanging(System.Nullable<bool> value);
    partial void OnPersonelAktifChanged();
    partial void OnSorumluOldDepartmanChanging(string value);
    partial void OnSorumluOldDepartmanChanged();
    partial void OnDepartmanIDChanging(System.Nullable<int> value);
    partial void OnDepartmanIDChanged();
    partial void OnIseBaslangicTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnIseBaslangicTarihiChanged();
    partial void OnAyrilmaTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnAyrilmaTarihiChanged();
    partial void OnSehirChanging(string value);
    partial void OnSehirChanged();
    partial void OnIlceChanging(string value);
    partial void OnIlceChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnTelefon1Changing(string value);
    partial void OnTelefon1Changed();
    partial void OnTelefon2Changing(string value);
    partial void OnTelefon2Changed();
    partial void OnWebAdresChanging(string value);
    partial void OnWebAdresChanged();
    partial void OnMailChanging(string value);
    partial void OnMailChanged();
    partial void OnSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSaveDateChanged();
    partial void OnSaveUserChanging(System.Nullable<int> value);
    partial void OnSaveUserChanged();
    partial void OnEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEditDateChanged();
    partial void OnEditUserChanging(System.Nullable<int> value);
    partial void OnEditUserChanged();
    partial void OnLastLoginChanging(System.Nullable<System.DateTime> value);
    partial void OnLastLoginChanged();
    #endregion
		
		public TBL_Personeller()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelKodu", DbType="NVarChar(30)")]
		public string PersonelKodu
		{
			get
			{
				return this._PersonelKodu;
			}
			set
			{
				if ((this._PersonelKodu != value))
				{
					this.OnPersonelKoduChanging(value);
					this.SendPropertyChanging();
					this._PersonelKodu = value;
					this.SendPropertyChanged("PersonelKodu");
					this.OnPersonelKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelAdiSoyadi", DbType="NVarChar(150)")]
		public string PersonelAdiSoyadi
		{
			get
			{
				return this._PersonelAdiSoyadi;
			}
			set
			{
				if ((this._PersonelAdiSoyadi != value))
				{
					this.OnPersonelAdiSoyadiChanging(value);
					this.SendPropertyChanging();
					this._PersonelAdiSoyadi = value;
					this.SendPropertyChanged("PersonelAdiSoyadi");
					this.OnPersonelAdiSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelKullaniciAdi", DbType="NVarChar(50)")]
		public string PersonelKullaniciAdi
		{
			get
			{
				return this._PersonelKullaniciAdi;
			}
			set
			{
				if ((this._PersonelKullaniciAdi != value))
				{
					this.OnPersonelKullaniciAdiChanging(value);
					this.SendPropertyChanging();
					this._PersonelKullaniciAdi = value;
					this.SendPropertyChanged("PersonelKullaniciAdi");
					this.OnPersonelKullaniciAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelSifre", DbType="NVarChar(50)")]
		public string PersonelSifre
		{
			get
			{
				return this._PersonelSifre;
			}
			set
			{
				if ((this._PersonelSifre != value))
				{
					this.OnPersonelSifreChanging(value);
					this.SendPropertyChanging();
					this._PersonelSifre = value;
					this.SendPropertyChanged("PersonelSifre");
					this.OnPersonelSifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelRutbe", DbType="NVarChar(50)")]
		public string PersonelRutbe
		{
			get
			{
				return this._PersonelRutbe;
			}
			set
			{
				if ((this._PersonelRutbe != value))
				{
					this.OnPersonelRutbeChanging(value);
					this.SendPropertyChanging();
					this._PersonelRutbe = value;
					this.SendPropertyChanged("PersonelRutbe");
					this.OnPersonelRutbeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelAktif", DbType="Bit")]
		public System.Nullable<bool> PersonelAktif
		{
			get
			{
				return this._PersonelAktif;
			}
			set
			{
				if ((this._PersonelAktif != value))
				{
					this.OnPersonelAktifChanging(value);
					this.SendPropertyChanging();
					this._PersonelAktif = value;
					this.SendPropertyChanged("PersonelAktif");
					this.OnPersonelAktifChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SorumluOldDepartman", DbType="NVarChar(50)")]
		public string SorumluOldDepartman
		{
			get
			{
				return this._SorumluOldDepartman;
			}
			set
			{
				if ((this._SorumluOldDepartman != value))
				{
					this.OnSorumluOldDepartmanChanging(value);
					this.SendPropertyChanging();
					this._SorumluOldDepartman = value;
					this.SendPropertyChanged("SorumluOldDepartman");
					this.OnSorumluOldDepartmanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmanID", DbType="Int")]
		public System.Nullable<int> DepartmanID
		{
			get
			{
				return this._DepartmanID;
			}
			set
			{
				if ((this._DepartmanID != value))
				{
					this.OnDepartmanIDChanging(value);
					this.SendPropertyChanging();
					this._DepartmanID = value;
					this.SendPropertyChanged("DepartmanID");
					this.OnDepartmanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IseBaslangicTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> IseBaslangicTarihi
		{
			get
			{
				return this._IseBaslangicTarihi;
			}
			set
			{
				if ((this._IseBaslangicTarihi != value))
				{
					this.OnIseBaslangicTarihiChanging(value);
					this.SendPropertyChanging();
					this._IseBaslangicTarihi = value;
					this.SendPropertyChanged("IseBaslangicTarihi");
					this.OnIseBaslangicTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AyrilmaTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> AyrilmaTarihi
		{
			get
			{
				return this._AyrilmaTarihi;
			}
			set
			{
				if ((this._AyrilmaTarihi != value))
				{
					this.OnAyrilmaTarihiChanging(value);
					this.SendPropertyChanging();
					this._AyrilmaTarihi = value;
					this.SendPropertyChanged("AyrilmaTarihi");
					this.OnAyrilmaTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sehir", DbType="NVarChar(30)")]
		public string Sehir
		{
			get
			{
				return this._Sehir;
			}
			set
			{
				if ((this._Sehir != value))
				{
					this.OnSehirChanging(value);
					this.SendPropertyChanging();
					this._Sehir = value;
					this.SendPropertyChanged("Sehir");
					this.OnSehirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilce", DbType="NVarChar(30)")]
		public string Ilce
		{
			get
			{
				return this._Ilce;
			}
			set
			{
				if ((this._Ilce != value))
				{
					this.OnIlceChanging(value);
					this.SendPropertyChanging();
					this._Ilce = value;
					this.SendPropertyChanged("Ilce");
					this.OnIlceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon1", DbType="NVarChar(16)")]
		public string Telefon1
		{
			get
			{
				return this._Telefon1;
			}
			set
			{
				if ((this._Telefon1 != value))
				{
					this.OnTelefon1Changing(value);
					this.SendPropertyChanging();
					this._Telefon1 = value;
					this.SendPropertyChanged("Telefon1");
					this.OnTelefon1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon2", DbType="NVarChar(16)")]
		public string Telefon2
		{
			get
			{
				return this._Telefon2;
			}
			set
			{
				if ((this._Telefon2 != value))
				{
					this.OnTelefon2Changing(value);
					this.SendPropertyChanging();
					this._Telefon2 = value;
					this.SendPropertyChanged("Telefon2");
					this.OnTelefon2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebAdres", DbType="NVarChar(150)")]
		public string WebAdres
		{
			get
			{
				return this._WebAdres;
			}
			set
			{
				if ((this._WebAdres != value))
				{
					this.OnWebAdresChanging(value);
					this.SendPropertyChanging();
					this._WebAdres = value;
					this.SendPropertyChanged("WebAdres");
					this.OnWebAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="NVarChar(250)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this.OnMailChanging(value);
					this.SendPropertyChanging();
					this._Mail = value;
					this.SendPropertyChanged("Mail");
					this.OnMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SaveDate
		{
			get
			{
				return this._SaveDate;
			}
			set
			{
				if ((this._SaveDate != value))
				{
					this.OnSaveDateChanging(value);
					this.SendPropertyChanging();
					this._SaveDate = value;
					this.SendPropertyChanged("SaveDate");
					this.OnSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveUser", DbType="Int")]
		public System.Nullable<int> SaveUser
		{
			get
			{
				return this._SaveUser;
			}
			set
			{
				if ((this._SaveUser != value))
				{
					this.OnSaveUserChanging(value);
					this.SendPropertyChanging();
					this._SaveUser = value;
					this.SendPropertyChanged("SaveUser");
					this.OnSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this.OnEditDateChanging(value);
					this.SendPropertyChanging();
					this._EditDate = value;
					this.SendPropertyChanged("EditDate");
					this.OnEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditUser", DbType="Int")]
		public System.Nullable<int> EditUser
		{
			get
			{
				return this._EditUser;
			}
			set
			{
				if ((this._EditUser != value))
				{
					this.OnEditUserChanging(value);
					this.SendPropertyChanging();
					this._EditUser = value;
					this.SendPropertyChanged("EditUser");
					this.OnEditUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLogin", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastLogin
		{
			get
			{
				return this._LastLogin;
			}
			set
			{
				if ((this._LastLogin != value))
				{
					this.OnLastLoginChanging(value);
					this.SendPropertyChanging();
					this._LastLogin = value;
					this.SendPropertyChanged("LastLogin");
					this.OnLastLoginChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_ZimmetIadeNeden")]
	public partial class TBL_ZimmetIadeNeden
	{
		
		private System.Nullable<int> _ID;
		
		private string _ZimmetIadeKodu;
		
		private string _ZimmetIadeNeden;
		
		private System.Nullable<System.DateTime> _SaveDate;
		
		private System.Nullable<int> _SaveUser;
		
		private System.Nullable<System.DateTime> _EditDate;
		
		private System.Nullable<int> _EditUser;
		
		public TBL_ZimmetIadeNeden()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZimmetIadeKodu", DbType="NVarChar(30)")]
		public string ZimmetIadeKodu
		{
			get
			{
				return this._ZimmetIadeKodu;
			}
			set
			{
				if ((this._ZimmetIadeKodu != value))
				{
					this._ZimmetIadeKodu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZimmetIadeNeden", DbType="NVarChar(150)")]
		public string ZimmetIadeNeden
		{
			get
			{
				return this._ZimmetIadeNeden;
			}
			set
			{
				if ((this._ZimmetIadeNeden != value))
				{
					this._ZimmetIadeNeden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SaveDate
		{
			get
			{
				return this._SaveDate;
			}
			set
			{
				if ((this._SaveDate != value))
				{
					this._SaveDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveUser", DbType="Int")]
		public System.Nullable<int> SaveUser
		{
			get
			{
				return this._SaveUser;
			}
			set
			{
				if ((this._SaveUser != value))
				{
					this._SaveUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this._EditDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditUser", DbType="Int")]
		public System.Nullable<int> EditUser
		{
			get
			{
				return this._EditUser;
			}
			set
			{
				if ((this._EditUser != value))
				{
					this._EditUser = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_Urunler")]
	public partial class VW_Urunler
	{
		
		private string _TeminKodu;
		
		private string _TeminAdi;
		
		private string _UrunTuruKodu;
		
		private string _UrunTuruAdi;
		
		private string _UrunAdi;
		
		private System.Nullable<decimal> _UrunAlisFiyat;
		
		private string _UrunBarkod;
		
		private string _UrunKodu;
		
		private string _UrunTuruAciklama;
		
		private System.Nullable<int> _UrunStokMiktari;
		
		private System.Nullable<System.DateTime> _UrunAlisTarihi;
		
		private string _UrunTeminSubeAdi;
		
		private System.Nullable<int> _UrunSaveUser;
		
		private System.Nullable<System.DateTime> _UrunSaveDate;
		
		private string _MarkaAdi;
		
		private string _MarkaKodu;
		
		private System.Nullable<int> _UrunEditUser;
		
		private System.Nullable<System.DateTime> _UrunEditDate;
		
		public VW_Urunler()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeminKodu", DbType="NVarChar(30)")]
		public string TeminKodu
		{
			get
			{
				return this._TeminKodu;
			}
			set
			{
				if ((this._TeminKodu != value))
				{
					this._TeminKodu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeminAdi", DbType="NVarChar(50)")]
		public string TeminAdi
		{
			get
			{
				return this._TeminAdi;
			}
			set
			{
				if ((this._TeminAdi != value))
				{
					this._TeminAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunTuruKodu", DbType="NVarChar(30)")]
		public string UrunTuruKodu
		{
			get
			{
				return this._UrunTuruKodu;
			}
			set
			{
				if ((this._UrunTuruKodu != value))
				{
					this._UrunTuruKodu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunTuruAdi", DbType="NVarChar(50)")]
		public string UrunTuruAdi
		{
			get
			{
				return this._UrunTuruAdi;
			}
			set
			{
				if ((this._UrunTuruAdi != value))
				{
					this._UrunTuruAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunAdi", DbType="NVarChar(50)")]
		public string UrunAdi
		{
			get
			{
				return this._UrunAdi;
			}
			set
			{
				if ((this._UrunAdi != value))
				{
					this._UrunAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunAlisFiyat", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> UrunAlisFiyat
		{
			get
			{
				return this._UrunAlisFiyat;
			}
			set
			{
				if ((this._UrunAlisFiyat != value))
				{
					this._UrunAlisFiyat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunBarkod", DbType="NVarChar(30)")]
		public string UrunBarkod
		{
			get
			{
				return this._UrunBarkod;
			}
			set
			{
				if ((this._UrunBarkod != value))
				{
					this._UrunBarkod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunKodu", DbType="NVarChar(20)")]
		public string UrunKodu
		{
			get
			{
				return this._UrunKodu;
			}
			set
			{
				if ((this._UrunKodu != value))
				{
					this._UrunKodu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunTuruAciklama", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string UrunTuruAciklama
		{
			get
			{
				return this._UrunTuruAciklama;
			}
			set
			{
				if ((this._UrunTuruAciklama != value))
				{
					this._UrunTuruAciklama = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunStokMiktari", DbType="Int")]
		public System.Nullable<int> UrunStokMiktari
		{
			get
			{
				return this._UrunStokMiktari;
			}
			set
			{
				if ((this._UrunStokMiktari != value))
				{
					this._UrunStokMiktari = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunAlisTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> UrunAlisTarihi
		{
			get
			{
				return this._UrunAlisTarihi;
			}
			set
			{
				if ((this._UrunAlisTarihi != value))
				{
					this._UrunAlisTarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunTeminSubeAdi", DbType="NVarChar(50)")]
		public string UrunTeminSubeAdi
		{
			get
			{
				return this._UrunTeminSubeAdi;
			}
			set
			{
				if ((this._UrunTeminSubeAdi != value))
				{
					this._UrunTeminSubeAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunSaveUser", DbType="Int")]
		public System.Nullable<int> UrunSaveUser
		{
			get
			{
				return this._UrunSaveUser;
			}
			set
			{
				if ((this._UrunSaveUser != value))
				{
					this._UrunSaveUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunSaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UrunSaveDate
		{
			get
			{
				return this._UrunSaveDate;
			}
			set
			{
				if ((this._UrunSaveDate != value))
				{
					this._UrunSaveDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkaAdi", DbType="NVarChar(30)")]
		public string MarkaAdi
		{
			get
			{
				return this._MarkaAdi;
			}
			set
			{
				if ((this._MarkaAdi != value))
				{
					this._MarkaAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkaKodu", DbType="NVarChar(30)")]
		public string MarkaKodu
		{
			get
			{
				return this._MarkaKodu;
			}
			set
			{
				if ((this._MarkaKodu != value))
				{
					this._MarkaKodu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunEditUser", DbType="Int")]
		public System.Nullable<int> UrunEditUser
		{
			get
			{
				return this._UrunEditUser;
			}
			set
			{
				if ((this._UrunEditUser != value))
				{
					this._UrunEditUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunEditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> UrunEditDate
		{
			get
			{
				return this._UrunEditDate;
			}
			set
			{
				if ((this._UrunEditDate != value))
				{
					this._UrunEditDate = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_ZimmetListesi")]
	public partial class VW_ZimmetListesi
	{
		
		private string _DepartmanAdi;
		
		private string _PersonelKodu;
		
		private string _PersonelAdiSoyadi;
		
		private string _PersonelRutbe;
		
		private string _SorumluOldDepartman;
		
		private System.Nullable<System.DateTime> _IseBaslangicTarihi;
		
		private string _Telefon1;
		
		private string _UrunKodu;
		
		private string _UrunAdi;
		
		private System.Nullable<decimal> _UrunAlisFiyat;
		
		private System.Nullable<System.DateTime> _TeslimTarihi;
		
		private string _ZimmetKodu;
		
		private System.Nullable<int> _SaveUser;
		
		private System.Nullable<System.DateTime> _EditDate;
		
		private System.Nullable<System.DateTime> _SaveDate;
		
		private System.Nullable<int> _EditUser;
		
		private int _ID;
		
		public VW_ZimmetListesi()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmanAdi", DbType="NVarChar(30)")]
		public string DepartmanAdi
		{
			get
			{
				return this._DepartmanAdi;
			}
			set
			{
				if ((this._DepartmanAdi != value))
				{
					this._DepartmanAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelKodu", DbType="NVarChar(30)")]
		public string PersonelKodu
		{
			get
			{
				return this._PersonelKodu;
			}
			set
			{
				if ((this._PersonelKodu != value))
				{
					this._PersonelKodu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelAdiSoyadi", DbType="NVarChar(150)")]
		public string PersonelAdiSoyadi
		{
			get
			{
				return this._PersonelAdiSoyadi;
			}
			set
			{
				if ((this._PersonelAdiSoyadi != value))
				{
					this._PersonelAdiSoyadi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelRutbe", DbType="NVarChar(50)")]
		public string PersonelRutbe
		{
			get
			{
				return this._PersonelRutbe;
			}
			set
			{
				if ((this._PersonelRutbe != value))
				{
					this._PersonelRutbe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SorumluOldDepartman", DbType="NVarChar(50)")]
		public string SorumluOldDepartman
		{
			get
			{
				return this._SorumluOldDepartman;
			}
			set
			{
				if ((this._SorumluOldDepartman != value))
				{
					this._SorumluOldDepartman = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IseBaslangicTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> IseBaslangicTarihi
		{
			get
			{
				return this._IseBaslangicTarihi;
			}
			set
			{
				if ((this._IseBaslangicTarihi != value))
				{
					this._IseBaslangicTarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon1", DbType="NVarChar(16)")]
		public string Telefon1
		{
			get
			{
				return this._Telefon1;
			}
			set
			{
				if ((this._Telefon1 != value))
				{
					this._Telefon1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunKodu", DbType="NVarChar(20)")]
		public string UrunKodu
		{
			get
			{
				return this._UrunKodu;
			}
			set
			{
				if ((this._UrunKodu != value))
				{
					this._UrunKodu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunAdi", DbType="NVarChar(50)")]
		public string UrunAdi
		{
			get
			{
				return this._UrunAdi;
			}
			set
			{
				if ((this._UrunAdi != value))
				{
					this._UrunAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunAlisFiyat", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> UrunAlisFiyat
		{
			get
			{
				return this._UrunAlisFiyat;
			}
			set
			{
				if ((this._UrunAlisFiyat != value))
				{
					this._UrunAlisFiyat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeslimTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> TeslimTarihi
		{
			get
			{
				return this._TeslimTarihi;
			}
			set
			{
				if ((this._TeslimTarihi != value))
				{
					this._TeslimTarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZimmetKodu", DbType="NVarChar(50)")]
		public string ZimmetKodu
		{
			get
			{
				return this._ZimmetKodu;
			}
			set
			{
				if ((this._ZimmetKodu != value))
				{
					this._ZimmetKodu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveUser", DbType="Int")]
		public System.Nullable<int> SaveUser
		{
			get
			{
				return this._SaveUser;
			}
			set
			{
				if ((this._SaveUser != value))
				{
					this._SaveUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this._EditDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SaveDate
		{
			get
			{
				return this._SaveDate;
			}
			set
			{
				if ((this._SaveDate != value))
				{
					this._SaveDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditUser", DbType="Int")]
		public System.Nullable<int> EditUser
		{
			get
			{
				return this._EditUser;
			}
			set
			{
				if ((this._EditUser != value))
				{
					this._EditUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_ZimmetHata")]
	public partial class TBL_ZimmetHata : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _ZimmetID;
		
		private System.Nullable<int> _PersonelID;
		
		private System.Nullable<int> _UrunID;
		
		private string _HataAciklama;
		
		private System.Nullable<System.DateTime> _IadeTarihi;
		
		private System.Nullable<int> _ZimmetHataIadeID;
		
		private System.Nullable<System.DateTime> _SaveDate;
		
		private System.Nullable<int> _SaveUser;
		
		private System.Nullable<System.DateTime> _EditDate;
		
		private System.Nullable<int> _EditUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnZimmetIDChanging(System.Nullable<int> value);
    partial void OnZimmetIDChanged();
    partial void OnPersonelIDChanging(System.Nullable<int> value);
    partial void OnPersonelIDChanged();
    partial void OnUrunIDChanging(System.Nullable<int> value);
    partial void OnUrunIDChanged();
    partial void OnHataAciklamaChanging(string value);
    partial void OnHataAciklamaChanged();
    partial void OnIadeTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnIadeTarihiChanged();
    partial void OnZimmetHataIadeIDChanging(System.Nullable<int> value);
    partial void OnZimmetHataIadeIDChanged();
    partial void OnSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSaveDateChanged();
    partial void OnSaveUserChanging(System.Nullable<int> value);
    partial void OnSaveUserChanged();
    partial void OnEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEditDateChanged();
    partial void OnEditUserChanging(System.Nullable<int> value);
    partial void OnEditUserChanged();
    #endregion
		
		public TBL_ZimmetHata()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZimmetID", DbType="Int")]
		public System.Nullable<int> ZimmetID
		{
			get
			{
				return this._ZimmetID;
			}
			set
			{
				if ((this._ZimmetID != value))
				{
					this.OnZimmetIDChanging(value);
					this.SendPropertyChanging();
					this._ZimmetID = value;
					this.SendPropertyChanged("ZimmetID");
					this.OnZimmetIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelID", DbType="Int")]
		public System.Nullable<int> PersonelID
		{
			get
			{
				return this._PersonelID;
			}
			set
			{
				if ((this._PersonelID != value))
				{
					this.OnPersonelIDChanging(value);
					this.SendPropertyChanging();
					this._PersonelID = value;
					this.SendPropertyChanged("PersonelID");
					this.OnPersonelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunID", DbType="Int")]
		public System.Nullable<int> UrunID
		{
			get
			{
				return this._UrunID;
			}
			set
			{
				if ((this._UrunID != value))
				{
					this.OnUrunIDChanging(value);
					this.SendPropertyChanging();
					this._UrunID = value;
					this.SendPropertyChanged("UrunID");
					this.OnUrunIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HataAciklama", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string HataAciklama
		{
			get
			{
				return this._HataAciklama;
			}
			set
			{
				if ((this._HataAciklama != value))
				{
					this.OnHataAciklamaChanging(value);
					this.SendPropertyChanging();
					this._HataAciklama = value;
					this.SendPropertyChanged("HataAciklama");
					this.OnHataAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IadeTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> IadeTarihi
		{
			get
			{
				return this._IadeTarihi;
			}
			set
			{
				if ((this._IadeTarihi != value))
				{
					this.OnIadeTarihiChanging(value);
					this.SendPropertyChanging();
					this._IadeTarihi = value;
					this.SendPropertyChanged("IadeTarihi");
					this.OnIadeTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZimmetHataIadeID", DbType="Int")]
		public System.Nullable<int> ZimmetHataIadeID
		{
			get
			{
				return this._ZimmetHataIadeID;
			}
			set
			{
				if ((this._ZimmetHataIadeID != value))
				{
					this.OnZimmetHataIadeIDChanging(value);
					this.SendPropertyChanging();
					this._ZimmetHataIadeID = value;
					this.SendPropertyChanged("ZimmetHataIadeID");
					this.OnZimmetHataIadeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SaveDate
		{
			get
			{
				return this._SaveDate;
			}
			set
			{
				if ((this._SaveDate != value))
				{
					this.OnSaveDateChanging(value);
					this.SendPropertyChanging();
					this._SaveDate = value;
					this.SendPropertyChanged("SaveDate");
					this.OnSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveUser", DbType="Int")]
		public System.Nullable<int> SaveUser
		{
			get
			{
				return this._SaveUser;
			}
			set
			{
				if ((this._SaveUser != value))
				{
					this.OnSaveUserChanging(value);
					this.SendPropertyChanging();
					this._SaveUser = value;
					this.SendPropertyChanged("SaveUser");
					this.OnSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this.OnEditDateChanging(value);
					this.SendPropertyChanging();
					this._EditDate = value;
					this.SendPropertyChanged("EditDate");
					this.OnEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditUser", DbType="Int")]
		public System.Nullable<int> EditUser
		{
			get
			{
				return this._EditUser;
			}
			set
			{
				if ((this._EditUser != value))
				{
					this.OnEditUserChanging(value);
					this.SendPropertyChanging();
					this._EditUser = value;
					this.SendPropertyChanged("EditUser");
					this.OnEditUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
